services:
  ros:
    build: .
    volumes:
      - ./src:/home/ros/src
    environment:
      - DISPLAY=host.docker.internal:0  # Set DISPLAY to Windows host
    network_mode: host  # Use host networking
    tty: true
    entrypoint: /bin/bash