services:
  ros-computer:
    build: ./containers
    container_name: ros
    volumes:
      - ./src:/home/ros/src
    environment:
      - DISPLAY=host.docker.internal:0  # Set DISPLAY to Windows host
    network_mode: host  # Use host networking
    ipc: host  # Use host IPC
    tty: true
    entrypoint: /bin/bash
  ros-vacuum:
    image: ros:humble-ros-base
    container_name: ros-vacuum
    volumes:
      - ./src:/home/ros/src
    network_mode: host  # Use host networking
    ipc: host  # Use host IPC
    tty: true
    entrypoint: /bin/bash